language: go
dist: xenial
sudo: required
services:
  - docker
jobs:
  include:
    - stage: "login"
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: "change dir"
      script: cd ${TRAVIS_BUILD_DIR}/dockerfiles
    - stage: build docker
      script: make docker_build_cpu
    - stage: build docker
      script: make docker_build_gpu
    - stage: push docker
      script: make docker_push_cpu
    - stage: push docker
      script: make docker_push_gpu
    - stage: update microbadger
      script: "curl -X POST https://hooks.microbadger.com/images/carml/go-caffe2/AeELmVfl5ucS37qg1Me7vJwauZY="
