# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: CPU
  steps:
  - bash: |
     docker login -u $(DOCKER_PASSWORD) -p $(DOCKER_PASSWORD)
     cd dockerfiles
     make docker_build_cpu
     make docker_push_cpu
     displayName: 'Build, tag and push cpu image'
- job: GPU
  steps:
  - bash: |
     docker login -u $(DOCKER_PASSWORD) -p $(DOCKER_PASSWORD)
     cd dockerfiles
     make docker_build_gpu
     make docker_push_gpu
     displayName: 'Build, tag and push gpu image'
